// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJGMmeSn4yPsT7MAvb9S5xmbfaa2Cp9Y',
    appId: '1:84458605564:web:2481b88af31d123b660079',
    messagingSenderId: '84458605564',
    projectId: 'dad-recipe-app',
    authDomain: 'dad-recipe-app.firebaseapp.com',
    storageBucket: 'dad-recipe-app.appspot.com',
    measurementId: 'G-45CJ3JM718',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCis06rWJv-ze5s9vUTMZaK-PTyKxyra9E',
    appId: '1:84458605564:android:c96c917e14afe519660079',
    messagingSenderId: '84458605564',
    projectId: 'dad-recipe-app',
    storageBucket: 'dad-recipe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGAel3BnLXJUskm-3p9KMSqc_2Y3FqKC4',
    appId: '1:84458605564:ios:ffcd7b732716edae660079',
    messagingSenderId: '84458605564',
    projectId: 'dad-recipe-app',
    storageBucket: 'dad-recipe-app.appspot.com',
    iosClientId: '84458605564-krk0ttn2medqabfksetr5e015t9b049p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dadRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGAel3BnLXJUskm-3p9KMSqc_2Y3FqKC4',
    appId: '1:84458605564:ios:ffcd7b732716edae660079',
    messagingSenderId: '84458605564',
    projectId: 'dad-recipe-app',
    storageBucket: 'dad-recipe-app.appspot.com',
    iosClientId: '84458605564-krk0ttn2medqabfksetr5e015t9b049p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dadRecipeApp',
  );
}
